// Core domain types for Hexwright, ported from the prototype's state tree.

export type BiomeKey =
  | "deep"
  | "ocean"
  | "shallow"
  | "beach"
  | "grass"
  | "savanna"
  | "desert"
  | "forest"
  | "jungle"
  | "taiga"
  | "tundra"
  | "swamp"
  | "hills"
  | "mountains"
  | "snow";

export type SizeKey = "small" | "medium" | "large";
export type EdgeKey = "sea" | "open";
export type ThemeKey = "parchment" | "dusk";
export type ViewKey = "gm" | "players";
export type Mode = "forge" | "table";
export type RouteMode = "manual" | "auto";

export type SpeedKey = "foot" | "mounted" | "ship";
export type SeasonKey = "spring" | "summer" | "autumn" | "winter";
export type WeatherKey = "clear" | "rain" | "storm" | "snow" | "fog";

/** Object kinds that can sit on the map. */
export type ObjectType =
  | "city"
  | "town"
  | "village"
  | "keep"
  | "ruin"
  | "dungeon"
  | "camp";

export interface Params {
  seed: string;
  size: SizeKey;
  hexMiles: number;
  sea: number;
  climate: number;
  wet: number;
  mountains: number;
  rivers: number;
  settlements: number;
  pois: number;
  edge: EdgeKey;
}

export interface Layers {
  grid: boolean;
  rivers: boolean;
  roads: boolean;
  borders: boolean;
  labels: boolean;
}

export interface Party {
  speed: SpeedKey;
  march: boolean;
  season: SeasonKey;
  weather: WeatherKey;
}

export interface Realm {
  id: number;
  name: string;
  color: string;
  seat: string;
  /** hex index of the realm's seat, used to recompute territory after edits. */
  seatHex: number;
  hexes: number;
}

export interface MapObject {
  id: string;
  /** true when generated by the forge; false when hand-placed (survives reforging). */
  gen: boolean;
  type: ObjectType;
  name: string;
  hex: number;
  pop: number;
  notes: string;
}

/**
 * A precomputed road segment (list of hex indices). Hoisted out of the paint
 * pass — the prototype computed these inside canvas paint, which was a hack.
 */
export type Road = number[];

export interface World {
  w: number;
  h: number;
  n: number;
  el: Float32Array;
  mo: Float32Array;
  tp: Float32Array;
  biome: BiomeKey[];
  land: Uint8Array;
  river: Uint8Array;
  flow: Float32Array;
  next: Int32Array;
  owner: Int16Array;
  realms: Realm[];
  roads: Road[];
  sea: number;
  edge: EdgeKey;
  seedName: string;
  hexMiles: number;
  /** world pixel size [width, height] at zoom 1. */
  px: [number, number];
}

export type Selected =
  | null
  | { kind: "object"; id: string }
  | { kind: "hex"; i: number };

export type Drag =
  | null
  | { kind: "brush" }
  | { kind: "obj"; id: string }
  | { kind: "wp"; n: number };

export interface JournalEntry {
  when: string;
  text: string;
  note: string;
  tone: string;
}

/** The serializable slice of state — everything a save file needs. */
export interface SaveFile {
  version: 1;
  params: Params;
  paint: Record<number, BiomeKey>;
  objects: MapObject[];
  realmNames: Record<number, string>;
  party: Party;
  day: number;
  journal: JournalEntry[];
  revealed: number[];
  layers: Layers;
  theme: ThemeKey;
}
